# Generated by Django 5.1.7 on 2025-03-19 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='user',
        ),
    ]
